baseURL = "https://www.pipajaya.com"
languageCode = "id-ID"
title = "Distributor Pipa PVC, HDPE, PPR"
assetDir = "static"

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
